ALTER TABLE `api_tokens` ADD CONSTRAINT `api_tokens_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `mst_items` ADD CONSTRAINT `mst_items_category_id_mst_item_categories_id_fk` FOREIGN KEY (`category_id`) REFERENCES `mst_item_categories`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_vessel_id_mst_vessels_id_fk` FOREIGN KEY (`vessel_id`) REFERENCES `mst_vessels`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_stocks` ADD CONSTRAINT `vessel_stocks_vessel_id_mst_vessels_id_fk` FOREIGN KEY (`vessel_id`) REFERENCES `mst_vessels`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_stocks` ADD CONSTRAINT `vessel_stocks_item_id_mst_items_id_fk` FOREIGN KEY (`item_id`) REFERENCES `mst_items`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_request_items` ADD CONSTRAINT `vessel_request_items_vessel_request_id_vessel_requests_id_fk` FOREIGN KEY (`vessel_request_id`) REFERENCES `vessel_requests`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_request_items` ADD CONSTRAINT `vessel_request_items_item_id_mst_items_id_fk` FOREIGN KEY (`item_id`) REFERENCES `mst_items`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_requests` ADD CONSTRAINT `vessel_requests_requested_by_users_id_fk` FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_requests` ADD CONSTRAINT `vessel_requests_vessel_id_mst_vessels_id_fk` FOREIGN KEY (`vessel_id`) REFERENCES `mst_vessels`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_requests` ADD CONSTRAINT `vessel_requests_reviewed_by_users_id_fk` FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_item_standard` ADD CONSTRAINT `vessel_item_standard_vessel_id_mst_vessels_id_fk` FOREIGN KEY (`vessel_id`) REFERENCES `mst_vessels`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `vessel_item_standard` ADD CONSTRAINT `vessel_item_standard_item_id_mst_items_id_fk` FOREIGN KEY (`item_id`) REFERENCES `mst_items`(`id`) ON DELETE no action ON UPDATE no action;